const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

const hotels = [
  // ===== DELHI =====
  { name: 'The Imperial New Delhi', location: 'Delhi, India', price: 22000, rating: 4.9, reviews: 3102, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800', featured: true, description: 'A landmark of elegance in the heart of New Delhi. The Imperial is a heritage hotel with stunning colonial architecture, lush gardens, and world-class dining experiences.', amenities: JSON.stringify(['Free WiFi', 'Spa', 'Pool', 'Heritage Architecture', 'Fine Dining', 'Fitness Centre']) },
  { name: 'The Leela Palace New Delhi', location: 'Delhi, India', price: 35000, rating: 5.0, reviews: 2455, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', featured: true, description: 'An ultra-luxury palace hotel inspired by Lutyens Delhi architecture, set amidst 9 acres of manicured gardens near the Diplomatic Enclave.', amenities: JSON.stringify(['Butler Service', 'Pool', 'Spa', 'Helicopter Transfers', 'Free WiFi', 'Concierge']) },
  { name: 'Taj Mahal Hotel New Delhi', location: 'Delhi, India', price: 28000, rating: 4.8, reviews: 4211, image: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=800', featured: false, description: 'Overlooking Lutyen\'s Delhi, this iconic hotel combines timeless Indian hospitality with contemporary luxury. Steps from India Gate and Parliament.', amenities: JSON.stringify(['Pool', 'Spa', 'Free WiFi', 'Multiple Restaurants', 'Airport Shuttle', 'Business Centre']) },
  { name: 'Roseate House Delhi Airport', location: 'Delhi, India', price: 12500, rating: 4.6, reviews: 1876, image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', featured: false, description: 'A contemporary boutique hotel right next to Indira Gandhi International Airport. Perfect for transit stays and business travelers.', amenities: JSON.stringify(['Airport Shuttle', 'Free WiFi', 'Restaurant', 'Gym', '24hr Room Service']) },
  { name: 'The Oberoi New Delhi', location: 'Delhi, India', price: 42000, rating: 4.9, reviews: 1934, image: 'https://images.unsplash.com/photo-1542314831-c6a4d14d8387?w=800', featured: false, description: 'Nestled amid 9 acres of beautiful gardens in the heart of New Delhi, The Oberoi offers personalized, intuitive service with sublime city views.', amenities: JSON.stringify(['Pool', 'Spa', 'Fine Dining', 'Free WiFi', 'Butler Service', 'Cigar Lounge']) },

  // ===== MUMBAI =====
  { name: 'Taj Mahal Palace Mumbai', location: 'Mumbai, India', price: 38000, rating: 5.0, reviews: 5120, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', featured: true, description: 'The majestic icon overlooking the Gateway of India and the Arabian Sea. A century of history and unparalleled luxury awaits at this celebrated landmark.', amenities: JSON.stringify(['Sea View', 'Heritage Property', 'Spa', 'Pool', 'Free WiFi', 'Butler Service']) },
  { name: 'Oberoi Trident Marine Drive', location: 'Mumbai, India', price: 25000, rating: 4.8, reviews: 3340, image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800', featured: false, description: 'Enjoy panoramic views of the Arabian Sea from Mumbai\'s iconic Marine Drive. Contemporary luxury and exceptional service on the Queen\'s Necklace.', amenities: JSON.stringify(['Sea View', 'Pool', 'Spa', 'Free WiFi', 'Fine Dining', 'Beach Access']) },
  { name: 'JW Marriott Mumbai Juhu', location: 'Mumbai, India', price: 19000, rating: 4.7, reviews: 2788, image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800', featured: false, description: 'Set on the sandy shores of Juhu Beach with stunning sunset views over the Arabian Sea. Multiple dining experiences and world-class spa.', amenities: JSON.stringify(['Beach Access', 'Pool', 'Spa', 'Free WiFi', 'Multiple Restaurants', 'Kids Club']) },
  { name: 'The St. Regis Mumbai', location: 'Mumbai, India', price: 32000, rating: 4.9, reviews: 1990, image: 'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800', featured: true, description: 'Soaring above Lower Parel, The St. Regis Mumbai stands as India\'s tallest hotel. Unmatched views, butler service, and iconic elegance.', amenities: JSON.stringify(['Sky Pool', 'Free WiFi', 'Butler Service', 'Spa', 'Rooftop Bar', 'City Views']) },
  { name: 'ITC Grand Central Mumbai', location: 'Mumbai, India', price: 15000, rating: 4.6, reviews: 2210, image: 'https://images.unsplash.com/photo-1582719478250-c89cfe4fd6e2?w=800', featured: false, description: 'A grand hotel in Mumbai\'s business district offering world-class amenities, authentic Indian cuisine, and warm Responsible Luxury hospitality.', amenities: JSON.stringify(['Pool', 'Free WiFi', 'Spa', 'Restaurant', 'Business Centre', 'Gym']) },

  // ===== GOA =====
  { name: 'Taj Exotica Goa', location: 'Goa, India', price: 28000, rating: 4.9, reviews: 4320, image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', featured: true, description: 'Nestled between lush palm groves and the Arabian Sea, Taj Exotica is a breathtaking beachfront resort on Benaulim beach in South Goa.', amenities: JSON.stringify(['Beach Access', 'Pool', 'Spa', 'Free WiFi', 'Diving', 'Water Sports']) },
  { name: 'The Leela Goa', location: 'Goa, India', price: 32000, rating: 4.8, reviews: 3870, image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', featured: false, description: 'A luxury beach resort on the Arabian Sea shores. Set across 75 acres with private lagoon, championship golf course, and spectacular facilities.', amenities: JSON.stringify(['Lagoon Access', 'Golf Course', 'Spa', 'Free WiFi', 'Multiple Pools', 'Beach Club']) },
  { name: 'Alila Diwa Goa', location: 'Goa, India', price: 18000, rating: 4.7, reviews: 2150, image: 'https://images.unsplash.com/photo-1596386461350-326ccb383e9f?w=800', featured: false, description: 'A serene sanctuary amidst emerald paddy fields. Alila Diwa is inspired by traditional Goan architecture and surrounded by lush nature.', amenities: JSON.stringify(['Rice Field Views', 'Pool', 'Spa', 'Free WiFi', 'Organic Restaurant', 'Yoga']) },
  { name: 'W Goa Vagator Beach', location: 'Goa, India', price: 22000, rating: 4.6, reviews: 1980, image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800', featured: false, description: 'Perched on the cliffs above Vagator beach, W Goa brings bold modern design and vibrant nightlife to North Goa\'s dramatic coastline.', amenities: JSON.stringify(['Cliff View', 'Infinity Pool', 'Beach Club', 'Free WiFi', 'DJ Nights', 'Spa']) },
  { name: 'Novotel Goa Candolim', location: 'Goa, India', price: 9500, rating: 4.4, reviews: 3420, image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800', featured: false, description: 'A family-friendly beachfront resort on Candolim beach. Great value with a beautiful pool, kids activities, and easy access to Goa\'s famous beach.', amenities: JSON.stringify(['Beach Access', 'Kids Club', 'Pool', 'Free WiFi', 'Restaurant', 'Watersports']) },

  // ===== JAIPUR =====
  { name: 'Rambagh Palace Jaipur', location: 'Jaipur, India', price: 55000, rating: 5.0, reviews: 2760, image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800', featured: true, description: 'Once the residence of the Maharaja of Jaipur, Rambagh Palace is a jewel of India with lavish suites, polo grounds, and regal heritage dining.', amenities: JSON.stringify(['Royal Suites', 'Polo Ground', 'Spa', 'Pool', 'Free WiFi', 'Heritage Tour']) },
  { name: 'Samode Palace Hotel', location: 'Jaipur, India', price: 38000, rating: 4.9, reviews: 1540, image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800', featured: false, description: 'A 475-year-old fortress palace offering royal Rajasthani hospitality. Exquisite frescoes, mirror-work interiors, and camel safaris await.', amenities: JSON.stringify(['Heritage Fortress', 'Camel Safari', 'Pool', 'Free WiFi', 'Folk Performances', 'Mughal Garden']) },
  { name: 'ITC Rajputana Jaipur', location: 'Jaipur, India', price: 16000, rating: 4.6, reviews: 3200, image: 'https://images.unsplash.com/photo-1542314831-c6a4d14d8387?w=800', featured: false, description: 'Built in the style of a traditional Rajput fortress, blending authentic Rajasthani décor with modern luxury in the heart of the Pink City.', amenities: JSON.stringify(['Pool', 'Spa', 'Free WiFi', 'Rajasthani Cuisine', 'Gym', 'Business Centre']) },
  { name: 'Fairmont Jaipur', location: 'Jaipur, India', price: 28000, rating: 4.8, reviews: 2100, image: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=800', featured: false, description: 'A palatial pink sandstone fortress set over 32 acres. Experience royal Rajasthani culture, elephant rides, and majestic courtyard dining.', amenities: JSON.stringify(['Elephant Rides', 'Pool', 'Spa', 'Free WiFi', '7 Restaurants', 'Tennis']) },
  { name: 'Hilton Jaipur', location: 'Jaipur, India', price: 11000, rating: 4.5, reviews: 1870, image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', featured: false, description: 'A contemporary luxury hotel in the heart of Jaipur with rooftop pool, Rajasthani cuisine, and proximity to the City Palace and Hawa Mahal.', amenities: JSON.stringify(['Rooftop Pool', 'Free WiFi', 'Spa', 'Restaurant', 'City Tours', 'Gym']) },

  // ===== UDAIPUR =====
  { name: 'Taj Lake Palace Udaipur', location: 'Udaipur, India', price: 65000, rating: 5.0, reviews: 3890, image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800', featured: true, description: 'The world\'s most romantic hotel — a 250-year-old white marble palace seemingly floating on Lake Pichola. A destination of legend and grand royalty.', amenities: JSON.stringify(['Lake Views', 'Boat Transfers', 'Heritage Suites', 'Spa', 'Pool', 'Royal Dining']) },
  { name: 'Oberoi Udaivilas', location: 'Udaipur, India', price: 72000, rating: 5.0, reviews: 2940, image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800', featured: false, description: 'Set on 50 acres on the banks of the Pichola Lake with sweeping views of Jag Mandir. Stunning architecture blending Rajput and Mughal styles.', amenities: JSON.stringify(['Lake View', 'Pool', 'Spa', 'Free WiFi', 'Butler Service', 'Wildlife Sanctuary']) },
  { name: 'Leela Palace Udaipur', location: 'Udaipur, India', price: 48000, rating: 4.9, reviews: 1780, image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800', featured: false, description: 'Perched on the serene Bansdara Hills with panoramic views of the Aravalli Range and Lake Pichola. Vibrant interiors and Indian heritage architecture.', amenities: JSON.stringify(['Aravalli Views', 'Pool', 'Spa', 'Free WiFi', 'Concierge', 'Heritage Walks']) },
  { name: 'Trident Udaipur', location: 'Udaipur, India', price: 14000, rating: 4.6, reviews: 2100, image: 'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800', featured: false, description: 'Nestled on the shores of Lake Pichola, Trident Udaipur offers beautiful lake-view rooms, Rajasthani décor, and warm hospitality at great value.', amenities: JSON.stringify(['Lake View', 'Pool', 'Spa', 'Free WiFi', 'Restaurant', 'Boat Rides']) },
  { name: 'Fateh Garh Udaipur', location: 'Udaipur, India', price: 9800, rating: 4.5, reviews: 1340, image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=800', featured: false, description: 'A heritage boutique hotel built within a centuries-old fortified royal estate. Stunning Aravalli hillside location with city and lake panoramas.', amenities: JSON.stringify(['Heritage Fort', 'Pool', 'Free WiFi', 'Sunset Views', 'Rajasthani Thali', 'Cultural Evenings']) },

  // ===== KERALA =====
  { name: 'Taj Green Cove Kovalam', location: 'Kerala, India', price: 24000, rating: 4.8, reviews: 2630, image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800', featured: true, description: 'Perched on a rocky promontory overlooking the sparkling Arabian Sea at Kovalam. A tropical sanctuary combining Ayurveda, beaches, and luxury.', amenities: JSON.stringify(['Sea View', 'Ayurveda Spa', 'Pool', 'Private Beach', 'Free WiFi', 'Yoga']) },
  { name: 'Kumarakom Lake Resort', location: 'Kerala, India', price: 32000, rating: 4.9, reviews: 1890, image: 'https://images.unsplash.com/photo-1582719478250-c89cfe4fd6e2?w=800', featured: false, description: 'A heritage lake resort on the shores of Vembanad Lake. Traditional Kerala architecture, backwater cruises, and rejuvenating Ayurvedic treatments.', amenities: JSON.stringify(['Backwater Views', 'Heritage Villas', 'Ayurveda', 'Houseboat', 'Free WiFi', 'Yoga']) },
  { name: 'Spice Village Thekkady', location: 'Kerala, India', price: 12000, rating: 4.7, reviews: 1420, image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800', featured: false, description: 'An eco-friendly village retreat amidst Periyar\'s spice plantations and wildlife sanctuary. Rustic luxury and authentic Keralan experiences.', amenities: JSON.stringify(['Wildlife Safari', 'Ayurveda', 'Spice Walks', 'Free WiFi', 'Eco Friendly', 'Organic Food']) },
  { name: 'Fragrant Nature Backwaters', location: 'Kerala, India', price: 8500, rating: 4.5, reviews: 980, image: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800', featured: false, description: 'A serene backwater resort near Kollam with houseboat rides, coconut grove walks, and authentic Kerala toddy and seafood experiences.', amenities: JSON.stringify(['Houseboat', 'Backwater Views', 'Seafood', 'Free WiFi', 'Fishing', 'Canoe Rides']) },
  { name: 'Coconut Lagoon Kumarakom', location: 'Kerala, India', price: 15000, rating: 4.6, reviews: 1650, image: 'https://images.unsplash.com/photo-1596386461350-326ccb383e9f?w=800', featured: false, description: 'An enchanting eco-resort accessible only by boat, deep in the Kerala backwaters. Named one of India\'s best boutique resorts.', amenities: JSON.stringify(['Boat Access Only', 'Backwaters', 'Ayurveda', 'Birdwatching', 'Free WiFi', 'Heritage Villas']) },

  // ===== AGRA =====
  { name: 'The Oberoi Amarvilas Agra', location: 'Agra, India', price: 58000, rating: 5.0, reviews: 4210, image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800', featured: true, description: 'Every room and suite has an uninterrupted view of the Taj Mahal. A Mughal-inspired palace hotel within walking distance of the world\'s most beautiful monument.', amenities: JSON.stringify(['Taj Mahal View', 'Pool', 'Spa', 'Free WiFi', 'Butler Service', 'Multiple Restaurants']) },
  { name: 'ITC Mughal Agra', location: 'Agra, India', price: 22000, rating: 4.8, reviews: 3100, image: 'https://images.unsplash.com/photo-1563911302283-d2bc129e7570?w=800', featured: false, description: 'A masterpiece of Mughal architecture set in 35 acres of beautiful Mughal gardens. Breathtaking Taj Mahal views and world-class cuisine.', amenities: JSON.stringify(['Taj View', 'Mughal Gardens', 'Spa', 'Pool', 'Free WiFi', 'Fine Dining']) },
  { name: 'Taj Hotel and Convention Centre', location: 'Agra, India', price: 15000, rating: 4.7, reviews: 2340, image: 'https://images.unsplash.com/photo-1542314831-c6a4d14d8387?w=800', featured: false, description: 'A comfortable luxury hotel close to the Taj Mahal with spacious rooms, Mughal-inspired décor, and expert guided heritage tours of Agra.', amenities: JSON.stringify(['Near Taj Mahal', 'Pool', 'Spa', 'Free WiFi', 'Heritage Tours', 'Multi-Cuisine Restaurant']) },
  { name: 'Radisson Hotel Agra', location: 'Agra, India', price: 8500, rating: 4.4, reviews: 1890, image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', featured: false, description: 'A modern hotel in Agra offering comfortable stays with great amenities and excellent access to the Golden Triangle monuments including Taj Mahal.', amenities: JSON.stringify(['Pool', 'Spa', 'Free WiFi', 'Restaurant', 'Gym', 'Business Centre']) },
  { name: 'Crystal Sarovar Premiere Agra', location: 'Agra, India', price: 6500, rating: 4.3, reviews: 1450, image: 'https://images.unsplash.com/photo-1596178060671-7a80dc8059ea?w=800', featured: false, description: 'A premium midscale hotel located minutes from Taj Mahal and Agra Fort, offering clean, modern rooms with warm hospitality and local tours.', amenities: JSON.stringify(['Free WiFi', 'Pool', 'Restaurant', 'Heritage Tours', 'Gym', 'Concierge']) },
];

async function main() {
  console.log('🌱 Seeding Indian hotels...');
  const hashedPassword = await bcrypt.hash('password123', 10);

  await prisma.user.upsert({
    where: { email: 'demo@wanderstay.com' },
    update: {},
    create: { email: 'demo@wanderstay.com', name: 'Demo User', password: hashedPassword, points: 1500 },
  });

  await prisma.promotion.upsert({ where: { code: 'SUMMER20' }, update: {}, create: { code: 'SUMMER20', discountPercent: 20, isActive: true } });
  await prisma.promotion.upsert({ where: { code: 'INDIA10' }, update: {}, create: { code: 'INDIA10', discountPercent: 10, isActive: true } });

  await prisma.booking.deleteMany({});
  await prisma.hotel.deleteMany({});

  for (const hotel of hotels) {
    await prisma.hotel.create({ data: hotel });
    process.stdout.write('.');
  }

  console.log(`\n✅ Seeded ${hotels.length} Indian hotels across Delhi, Mumbai, Goa, Jaipur, Udaipur, Kerala & Agra!`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exit(1); });
